# -*- coding: utf-8 -*-
"""scraper_demo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g4MXSpIhX2ZM87Z1TZgcmBpFGKbgFVmM

###**scraper_demo.py**

###**Simple demonstration of how Flipkart scraping logic works.**
"""

import requests
from bs4 import BeautifulSoup

URL = "https://www.flipkart.com/search?q=mobiles&page=1"

headers = {"User-Agent": "Mozilla/5.0"}
response = requests.get(URL, headers=headers)
soup = BeautifulSoup(response.text, "html.parser")

products = []

cards = soup.select("div._2kHMtA")

for card in cards[:5]:  # demo limit
    name = card.select_one("div._4rR01T")
    price = card.select_one("div._30jeq3")
    rating = card.select_one("div._3LWZlK")

    products.append({
        "product_name": name.text.strip() if name else None,
        "selling_price": price.text.strip() if price else None,
        "rating": rating.text.strip() if rating else None
    })

print(products)
